### ISSUE TITLE
Pneumatic Diversity Vents

### ISSUE THREAD

**Issue by UmbraSprite** [BEEmod/BEEMOD#7]
I set up one of these guys and used a portal to have it pull cubes through the portal.  In this case the distant portal was an orange AutoPortal and I created the blue portal near the PDV.  Everything worked fine however the orange particle effect remained outside of the AutoPortal even after it closed.  Clearly not game breaking but it seemed like one of those scenario's that may not have been encountered during development.

Thanks for this great mod!

**Comment by vrad-exe** [comment]
Valve never fixed a lot of bugs with the Diversity Vent. Closing a portal doesn't actually remove the entity, it just hides it (this is intentional). But the Diversity Vent might not be taking that into account, and displaying the particles anyway. I don't think it's really fixable without access to the source code.

**Comment by TeamSpen210** [comment]
Actually BEE autoportals kill the portal when closed, so it's probably the vent being dumb.
